version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"

  nodejs:
    build:
      context: websocket
      dockerfile: Dockerfile
    container_name: websocket
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
    driver: local